### ISSUE TITLE
Firefox display issue

### ISSUE THREAD

**Issue by tigattack** [mdotshell/wastebin#6]
It seems that the code section isn't properly displayed in Firefox. The top bar also appears to be offset from the top a little.

Firefox:
![image](https://user-images.githubusercontent.com/10629864/87073704-bed5b600-c215-11ea-8706-af2da0d73590.png)

Chrome:
![image](https://user-images.githubusercontent.com/10629864/87073808-de6cde80-c215-11ea-8292-819aa93e7f3a.png)

**Comment by mdotshell** [comment]
Should be resolved with commit f53a40acf39d5973c7788302a7e25f9156df20fb

**Comment by tigattack** [comment]
Sorted, cheers dude.
